### ISSUE TITLE
微信小程序native例子不起作用

### ISSUE THREAD

**Issue by chocoford-zhang** [sonofmagic/tailwindcss-miniprogram-preset#1]
我直接用开发工具打开native
运行`yarn`安装依赖
然后运行`yarn dev`
发现`tailwindcss`样式并未生效

**Comment by sonofmagic** [comment]
在 `package.json` 里，我写了2个脚本，一个`yarn dev` : 是编译 `typescript` 到小程序的，一个 `yarn css` 那个就是来编译 `tailwindcss`和 `sass` 的，这里是为了把脚本区分开，实际项目中，这2个脚本可以合并。所以你在使用的时候，可以先 `yarn dev` 再 `yarn css`

**Comment by sonofmagic** [comment]
`yarn dev` `yarn css` `yarn purge:css` 分别代表，编译 ts , 编译完整版 `tailwind` 和 `scss` 和根据 `wxml`编译 **purge** 过的 `wxss`

**Comment by chocoford-zhang** [comment]
@sonofmagic thx，顺带提一点，example里`presets: [require('../../src/index')]`在运行`yarn css`时会报错。手动安装`tailwindcss-miniprogram-preset`后改用`presets: [require('tailwindcss-miniprogram-preset')]`就可以成功运行

**Comment by chocoford-zhang** [comment]
我新建新项目后，会得到`./app.wxss(1:21): unexpected token ';'`的错误

**Comment by sonofmagic** [comment]
我自己试了一下，这 2 种 情况都没有出现，请问你是如何操作的？
我是先， `git clone` 这个项目，然后 安装 `tailwindcss-miniprogram-preset` 根目录的依赖(yarn)，然后 `cd examples/native`  (yarn)
然后，依次执行, `yarn dev` `yarn css` ，再用微信开发者工具打开，发现是起作用的。

能否把你编译失败的文件发我一下？

**Comment by sonofmagic** [comment]
> @sonofmagic thx，顺带提一点，example里`presets: [require('../../src/index')]`在运行`yarn css`时会报错。手动安装`tailwindcss-miniprogram-preset`后改用`presets: [require('tailwindcss-miniprogram-preset')]`就可以成功运行

这个应该是没有安装根目录的依赖导致的，因为这个例子，我直接依赖了源码了
直接换成`tailwindcss-miniprogram-preset` 也挺好

**Comment by chocoford-zhang** [comment]
我用你的`example`没问题，就是跟着你的guide会出问题，不知道遗漏了什么。

`yarn dev`以及`yarn css`命令没有问题，也生成了相应的wxss文件。就是小程序会报错
## 相关文件
### package.json
```json
{
...
  "scripts": {
    "dev": "tsc -w",
    "css": "node scripts/build.js",
    "purge:css": "cross-env NODE_ENV=production node scripts/build.js"
  },
  "keywords": [],
  "author": "",
  "license": "",
  "dependencies": {},
  "devDependencies": {
    "autoprefixer": "^10.4.0",
    "chokidar": "^3.5.2",
    "fibers": "^5.0.0",
    "miniprogram-api-typings": "^3.4.4",
    "postcss": "^8.3.11",
    "sass": "^1.43.4",
    "tailwindcss": "^2.2.19",
    "tailwindcss-miniprogram-preset": "^1.0.7",
    "tsc": "^2.0.3",
    "typescript": "^4.4.4"
  }
}

```
### postcss.config.js
```javascript
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('tailwindcss')
  ]
}
```

### tailwind.config.js
```javascript
module.exports = {
  purge: {
    // enabled: true,
    content: ['**/*.wxml']
    // css: ['**/*.wxss']
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
  presets: [require('tailwindcss-miniprogram-preset')]

}

```

### app.scss
```scss
@tailwind utilities;
```

**Comment by sonofmagic** [comment]
可否把报错的 `app.wxss` 发我一下，我的微信号 https://github.com/sonofmagic 这里有，扫码就行
