### ISSUE TITLE
我在 Taro 项目中集成了 Tailwind.css，部分内容未生效

### ISSUE THREAD

**Issue by hejianghu** [sonofmagic/tailwindcss-miniprogram-preset#5]
你好！我在添加了 presets 之后，Tailwind.css 官方提供的 `p-1` 之类的 rem 被正确解析成 rpx，但是当使用了不在[官方提供的范围内的尺寸](https://www.tailwindcss.cn/docs/padding)，如 `p-101`，好像生成了一个 rem 单位的值，并没有被转化成 rpx，请问这个能处理吗？

**Comment by sonofmagic** [comment]
这个应该是tailwindcss [just-in-time-mode](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode) 模式，它可以根据参数动态生成 css , 需要在 `taiwind.config.js` 开启 `mode: 'jit'` 来启用 。

但**是由于小程序 `wxml` 的 `class` 不支持像 `[,],\,/` 这类的变量命名, 同时`wxss`的选择器也有限**，故目前暂时做不到完美的 `jit`，不过我接下来的计划就是支持 `jit`. 

具体，我会写 `postcss` 插件来对 `tailwindcss` 的`class`进一步转义，从而不尽可能，不需要修改多少代码，就能带来原汁原味的 `tailwindcss`

**Comment by hejianghu** [comment]
感谢大佬

**Comment by sonofmagic** [comment]
`jit` 模式，现在可以直接使用 [weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) , 现在会在打包代码的时候，自动转义，不需要记忆和阉割 那些 `jit` 不兼容的写法，体验原汁原味的 `tailwindcss jit` 引擎把。
