### ISSUE TITLE
有支持tailwindcss 3的计划吗？

### ISSUE THREAD

**Issue by qichunren** [sonofmagic/tailwindcss-miniprogram-preset#8]

**Comment by sonofmagic** [comment]
有的，不过三最大的改动在于即时编译模式 (jit)，这点小程序假如不能使用的话，升级了三也没啥意义。这点最近正在编写一个 webpack-plugin 来 rename 小程序的 tailwindcss class, 只有这样才能支持 v3 最重要的 jit 模式。

**Comment by sonofmagic** [comment]
目前已经编写了[weapp-tailwindcss-webpack-plugin](https://github.com/sonofmagic/weapp-tailwindcss-webpack-plugin) 用来支持 `tailwindcss 3` 中强大的 `jit` 引擎.
LOL
